### ISSUE TITLE
getBookByAuthor test doesn't work

### ISSUE THREAD

**Issue by Terbish** [Terbish/webdev#1]
here's the output:
Charles Dickens 1
[
  {
    title: 'A Tale of Two Cities',
    subtitle: 'A novel',
    publicationDate: '1859-01-01',
    tags: [ 'historical', 'fiction' ],
    primaryAuthorId: 1
  }
]
undefined
GET /books/author/Charles%20Dickens 404 0.348 ms - 28
    1) should get books by author

  6 passing (35ms)
  1 failing

  1) Book Routes
       should get books by author:
     Error: expected 200 "OK", got 404 "Not Found"
      at Context.<anonymous> (file:///home/user/Code/webdev/server/test/book.test.js:37:85)
      at process.processImmediate (node:internal/timers:478:21)
  ----
      at Test._assertStatus (node_modules/supertest/lib/test.js:252:14)
      at /home/user/Code/webdev/server/node_modules/supertest/lib/test.js:308:13
      at Test._assertFunction (node_modules/supertest/lib/test.js:285:13)
      at Test.assert (node_modules/supertest/lib/test.js:164:23)
      at Server.localAssert (node_modules/supertest/lib/test.js:120:14)
      at Object.onceWrapper (node:events:632:28)
      at Server.emit (node:events:518:28)
      at emitCloseNT (node:net:2279:8)
      at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

**Comment by Terbish** [comment]
it works when manually tested the endpoints. issue potentially exists in testing code, proceed with manual testing for now
